### ISSUE TITLE
Linking overflow

### ISSUE THREAD

**Issue by magore** [apuder/PocketTRS#10]
I am using the 4.2 version of the espresive tools as doumented and the latests git clone of your project as per your documenation.
Here is the full build log that also includes the git clone, etc
[PocketTRS-build-log.txt](https://github.com/apuder/PocketTRS/files/6882595/PocketTRS-build-log.txt)

Here is just the link part that fails with /bin/ld: region `dram0_0_seg' overflowed by 132480 bytes
[link-error.txt](https://github.com/apuder/PocketTRS/files/6882580/link-error.txt)

You likely want to add menu_config options to the documenation or at least add CMakeLists.txt options that you need to compile and link

**Comment by magore** [comment]
The mistake was running menu_config even though I did not change any settings it reset several options. The solution is to NOT run menu_config on the project given that the settings are already in the project

**Comment by apuder** [comment]
I left the wrong instructions on your other issue. The instructions I mentioned are for TRS-IO; not PocketTRS. You should be able to compile out of the box without running menuconfig. Be sure to use branch ttgo.
