### ISSUE TITLE
partitions.csv needs to be specified in menu_config

### ISSUE THREAD

**Issue by magore** [apuder/PocketTRS#11]
Custom Partition Table must specify partitions.csv - not documented in  build instructions - in fact no  menu_config options are specified in the build instructions

**Comment by apuder** [comment]
Can you please give branch ttgo a try? Make use you set the correct model number in menuconfig. cd src/esp;idf.py build.

**Comment by magore** [comment]
Sorry - the problem was running menu_config reset the defaults
fixed
