### ISSUE TITLE
Expand ReadMe

### ISSUE THREAD

**Issue by OzHawk** [apuder/PocketTRS#5]
Sorry to raise an issue, but without any sort of discussion forum (GitHubs issue not yours) it’s difficult to start a discussion about a project.

I’m interested to know more about your project.
Does it use the standard Fabgl hardware or the TTGO VGA32 version?
Does it use the WiFi to transfer files?
Does it interface to the SD card for a file system?

Cheers,
Mike

**Comment by apuder** [comment]
Sorry for the sparse (i.e., non-existing) documentation. We'll work on that soon. To answer your question: we are using the FabGL library, but we have custom hardware (i.e., we are not using the FabGL reference boards). We use an ESP-WROVER-B module that has built-in Wifi. You have access to TCP sockets from within the TRS emulation and you can also read/write files from a mounted SMB share. But we do not support SD cards (we use SMB shares instead). You can check the "kicad" folder for the schematics and Gerber files.

**Comment by OzHawk** [comment]
Thanks Arno.
I was hoping for an image of the schematic, so I don’t have to install Kicad to view it.  I was interested to see what pins you have assigned to the various functions, and whether my FabGL boards will be compatible, or whether I will need to make a new board.
Without looking at the schematics, I’m guessing you’re using the ESP32 module on its own, like on the TTGO VGA32 boards, rather than using a development board like Fabrizio used.
I know that the TTGO VGA32 board is compatible with the FabGL dev board for everything except the SD card.

**Comment by apuder** [comment]
Send me a private message and I'll reply with a PDF of the schematics.

**Comment by OzHawk** [comment]
Sorry Arno, but I'm not sure what address to send a message to.  GitHub doesn't seem to have a Private Messaging system.
