### ISSUE TITLE
Compiled binary

### ISSUE THREAD

**Issue by MichaelM4** [apuder/PocketTRS#6]
Hello,

Is the compiled binary for the ESP32-WROVER-B available?

Thanks,
Mike

**Comment by apuder** [comment]
I would strongly encourage you to compile from source. You will need the tools for flashing anyways. Make sure you use version 3.3.4 of the ESP-IDF: https://docs.espressif.com/projects/esp-idf/en/v3.3.4/index.html
Follow the instructions on how to install the ESP-IDF toolchain for your platform. Then git clone this repo and run "make". That's it!
