### ISSUE TITLE
Which gerber should I use?

### ISSUE THREAD

**Issue by johnddias** [apuder/PocketTRS#7]
Hi Arno, saw you present on Trash Talk Live and want to build one. Which grb file(s) do I need to use for the fab order?

**Comment by apuder** [comment]
Please hold off for now. @jaquinn will soon push updated Gerber files. Just watch commits on this repo.

**Comment by apuder** [comment]
John: it seems there was a real-live race condition: Andrew updated the PCB while I was typing my last comment. You could be able to ZIP up the v2.2 directory and submit it to your preferred fab. Please let us know if you run into problems.

**Comment by johnddias** [comment]
Fantastic, thanks so much for this awesome project!
